xm_main_accueil:
    path:     /
    defaults: { _controller: XmMainBundle:Default:index }

xm_main_guide:
    path:     /guide
    defaults: { _controller: XmMainBundle:Default:guide}

xm_main_connexion:
    path:     /connexion
    defaults: { _controller: XmMainBundle:Security:login }

xm_main_validation_connexion:
     path:     /connexion_validation

xm_main_deconnexion:
    path:     /deconnexion

utilisateur_new:
    path:     /inscription
    defaults: { _controller: "XmMainBundle:Default:new" }

utilisateur_create:
    path:     /inscription_validation
    defaults: { _controller: "XmMainBundle:Default:create" }
    methods:  POST

utilisateur_reset:
    path:     /{email}/recuperation
    defaults: { _controller: "XmMainBundle:Default:reset" }