xm_main_accueil:
    path:     /
    defaults: { _controller: XmMainBundle:Default:index }

xm_main_guide:
    path:     /guide
    defaults: { _controller: XmMainBundle:Default:guide}

xm_main_error:
    path:     /error403
    defaults: { _controller: XmMainBundle:Default:error }


xm_main_connexion:
    path:     /connexion
    defaults: { _controller: XmMainBundle:Security:login }

utilisateur_reset:
    path:     /recuperation
    defaults: { _controller: "XmMainBundle:Security:reset" }
    methods:  POST