imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

services :
     login_listener :
           class : Xm\UserBundle\Listener\LoginListener
           tags:
                 - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }

     xm_user_registration:
           class: Xm\UserBundle\Form\UserType
           tags:
                 - { name: form.type }
           arguments: ["%fos_user.model.user.class%"]

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:           true
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources: ['bootstrap_3_layout.html.twig']

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport:  gmail
    username:   xarrmatt@gmail.com
    password:   DoorWaarKepp

# JMS security extra configuration
jms_security_extra:
    # Whether you want to secure all services (true), or only secure specific
    # services (false); see also below
    secure_all_services: false
    # Enables expression language
    expressions: true

liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~
        my_thumb:
            quality: 100
            filters:
                thumbnail: { size: [120, 90], mode: inset }
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: secured_area
    user_class: Xm\UserBundle\Entity\Utilisateur
    registration:
        confirmation:
            enabled: true
        form:
            type:   xm_user_registration
    from_email:
        address:        xarrmatt@gmail.com
        sender_name:    Nagn Dem
    resetting:
        email:
            from_email:
                address:       xarrmatt@gmail.com
                sender_name:    Nagn Dem

fos_message:
      db_driver:          orm
      thread_class:       Xm\MessageBundle\Entity\Thread
      message_class:      Xm\MessageBundle\Entity\Message
      new_thread_form:
          type:               fos_message.new_thread_multiple_form.type
          handler:            fos_message.new_thread_multiple_form.handler
          model:              FOS\MessageBundle\FormModel\NewThreadMultipleMessage
          name:               message


knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: twitter_bootstrap_v3_pagination.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template


