security:
     access_denied_url: xm_main_error

     encoders:
        Xm\UserBundle\Entity\Utilisateur: bcrypt

     role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

     providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

     firewalls:
         secured_area :
           pattern: ^(/utilisateurs|/login_check|/logout|/covoiturage/|/messages/)
           anonymous: false
           logout:
               path: /logout
               target : /
               intention: logout
           context : utilisateur

           remember_me:
             key: someS3cretKey
             lifetime: 300 
             path: /
             domain : ~

           form_login:
               provider : fos_userbundle 
               csrf_provider: security.csrf.token_manager
               failure_path:   xm_main_connexion
               login_path :   xm_main_connexion

         mixed_path:
           pattern: ^(/|guide)
           anonymous: true
           context : utilisateur

         unsecured_area :
           pattern : ^/(/login|/inscription$|/reinitialisation$)
           anonymous: true

     access_control :
        - { path: (/connexion|/recuperation) ,access : "!isAuthenticated()"}
        - { path: (^/utilisateurs/|/covoiturage/|/messages/|/confirm$ ), role: ROLE_USER }
