message:
    path:     /
    defaults: { _controller: "XmUserBundle:Message:index" }

message_new:
    path:     /nouveau
    defaults: { _controller: "XmUserBundle:Message:new" }

message_show:
    path:     /id/{username}
    defaults: { _controller: "XmUserBundle:Message:show" }

message_create:
    path:     /creer
    defaults: { _controller: "XmUserBundle:Message:create" }
    methods:  POST

message_delete:
    path:     /{username}/{id}/supprimer
    defaults: { _controller: "XmUserBundle:Message:delete" }
    methods:  [POST, DELETE]