Xmm\UserBundle\Entity\Utilisateur:
    properties:
        telephone:
            - Length:
                min: 9
                max: 9
                minMessage: "Votre nom doit faire au moins {{ limit }} caractères"
                maxMessage: "Votre nom ne peut pas être plus long que {{ limit }} caractères"
