Covoiturage:
    type: entity
    table: Covoiturage
    indexes:
        IDX_AE5B115E497832A6:
            columns:
                - ville_depart_id
        IDX_AE5B115E34AC9A4B:
            columns:
                - ville_arrivee_id
        IDX_AE5B115E56D142FC:
            columns:
                - initiateur_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        placesDispo:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: places_dispo
        dateDepart:
            type: date
            nullable: false
            comment: ''
            column: date_depart
        dateRetour:
            type: date
            nullable: false
            comment: ''
            column: date_retour
        heureDepart:
            type: time
            nullable: false
            comment: ''
            column: heure_depart
        heureRetour:
            type: time
            nullable: false
            comment: ''
            column: heure_retour
        addressDepart:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: address_depart
        addressRetour:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: address_retour
        resume:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
    manyToOne:
        initiateur:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                initiateur_id:
                    referencedColumnName: id
            orphanRemoval: false
        villeArrivee:
            targetEntity: Ville
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                ville_arrivee_id:
                    referencedColumnName: id
            orphanRemoval: false
        villeDepart:
            targetEntity: Ville
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                ville_depart_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
