Escale:
    type: entity
    table: Escale
    indexes:
        Escale_ibfk_3:
            columns:
                - villeB_id
        Escale_ibfk_4:
            columns:
                - ref_covoiturage
        IDX_C433E8E5724E2796:
            columns:
                - villeA_id
    id: {  }
    fields:
        numeroEscale:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: numero_escale
        prixTroncon:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            column: prix_troncon
    oneToOne:
        villea:
            targetEntity: Ville
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                villeA_id:
                    referencedColumnName: id
            orphanRemoval: false
        villeb:
            targetEntity: Ville
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                villeB_id:
                    referencedColumnName: id
            orphanRemoval: false
        refCovoiturage:
            targetEntity: Covoiturage
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                ref_covoiturage:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
