Message:
    type: entity
    table: Message
    indexes:
        IDX_790009E3F624B39D:
            columns:
                - sender_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        object:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        content:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        sendDate:
            type: datetime
            nullable: false
            comment: ''
            column: send_date
    manyToOne:
        sender:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                sender_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
