User:
    type: entity
    table: User
    indexes:
        IDX_2DA17977A73F0036:
            columns:
                - ville_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        passwords:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        prenom:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        nom:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        dateNaissance:
            type: date
            nullable: false
            comment: ''
            column: date_naissance
        email:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        telephone:
            type: decimal
            nullable: false
            precision: 10
            scale: 0
            comment: ''
        address:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        etatCompte:
            type: boolean
            nullable: false
            comment: ''
            column: etat_compte
    manyToOne:
        ville:
            targetEntity: Ville
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                ville_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
