Ville:
    type: entity
    table: Ville
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nomVille:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            column: nom_ville
    lifecycleCallbacks: {  }
