<?php

namespace Xm\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends EntityRepository
{ 
   /* 

	$query = $this->getEntityManager()->createQuery('

              SELECT p, c FROM AcmeStoreBundle:Product p
              JOIN p.category c

               WHERE p.id = :id'

                                               )->setParameter('id', $id);

	try {

	         return $query->getSingleResult();
	    } catch (\Doctrine\ORM\NoResultException $e) 
	   
	   {
	      return null;
	   }

    */
	
}
